### ISSUE TITLE
Getting Unauthenticated

### ISSUE THREAD

**Issue by bhuvaneshwariarkala** [GBSEcom/java#2] opened 2020-08-04 04:23 UTC
Hi team,

I am trying to integrate this lib into one of our product. But iam getitng below error,

Exception when calling AuthenticationApi#getAccessToken
com.github.GBSEcom.client.ApiException: Unauthenticated

While using any APIs.

Can I know what exactly needed here?

Thanks

**Comment by ericmargules** [comment] 2020-08-04 20:12
@bhuvaneshwariarkala Have you provided the correct merchant credentials where required in the sample code?

**Comment by bhuvaneshwariarkala** [comment] 2020-08-05 05:10
Yes, i have provided apisecret and apikey. And below is my code.

final String basePath = "https://cert.api.firstdata.com/gateway/v2";
		final String apiSecret = "XXXXXXxxxxx";
		final String apiKey = "XXXXXXXXXX";
		final MerchantCredentials creds = MerchantCredentials.of(apiSecret, apiKey);
		final ClientContext context = ClientContextImpl.create(creds, basePath);
		final ClientFactory factory = context.getFactory();
		final AuthenticationApi api = factory.getAuthenticationApi();
		final AccessTokenRequest req = new AccessTokenRequest();
		req.domain("somedomain.com");
		req.token("gfgF92JHDJFjxcJHCQ23IbI12D");
		req.publicKeyRequired(false);

		try {
			final AccessTokenResponse result = api.getAccessToken(req);
			System.out.println(result);
		} catch (ApiException e) {
			System.err.println("Exception when calling AuthenticationApi#getAccessToken");
			e.printStackTrace();
		}


Please let me know what is missing here?

Thanks

**Comment by ericmargules** [comment] 2020-08-05 14:03
@bhuvaneshwariarkala are you using production credentials or test credentials?

**Comment by bhuvaneshwariarkala** [comment] 2020-08-05 16:08
Hi, 
I tried with test and prod as well. Both shows same error, unauthenticated

Thanks

**Comment by ericmargules** [comment] 2020-08-05 16:31
Please reach out to integration-support@firstdata.com. It seems there's some issue with your credentials.

**Comment by sunil-m2minmotion** [comment] 2020-08-14 00:11
@bhuvaneshwariarkala 

Looks like you are using the sample code from "Getting Started". I see that the sample use com.github.GBSEcom.simple.*, but the latest 6.12 changes were not applied to simple package:
simple shows 6.11: https://github.com/GBSEcom/java/tree/master/src/main/java/com/github/GBSEcom 

I think the AuthenticationApi from api package should be used: https://github.com/GBSEcom/java/tree/master/src/main/java/com/github/GBSEcom/api
With all the changes to 6.12, it would have been good to show one sample/example of authorize, tokenize and charge a card.


cc:@ericmargules

**Comment by sunil-wenable** [comment] 2020-08-14 00:13
@bhuvaneshwariarkala

Looks like you are using the sample code from "Getting Started". I see that the sample use com.github.GBSEcom.simple.*, but the latest 6.12 changes were not applied to simple package:
simple shows 6.11: https://github.com/GBSEcom/java/tree/master/src/main/java/com/github/GBSEcom

I think the AuthenticationApi from api package should be used: https://github.com/GBSEcom/java/tree/master/src/main/java/com/github/GBSEcom/api
With all the changes to 6.12, it would have been good to show one sample/example of authorize, tokenize and charge a card.

cc:@ericmargules

**Comment by ericmargules** [comment] 2020-08-14 00:27
@sunil-wenable there were no changes to that package for 6.12. The sample code from Getting Started works with appropriate credentials. This has been confirmed repeated.

**Comment by ericmargules** [comment] 2020-08-14 00:36
@bhuvaneshwariarkala if you have any updates, let me know, otherwise I will close this issue. Thanks!

**Closed** 2020-09-28 17:02 UTC
